---
title: "Capstone Project"
author: "Yaoli Ma"
date: "7/16/2019"
output: pdf_document 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
library(tidyverse)
library(tidycensus)
library(lubridate)
library(sf)
library(stargazer)
library(haven)
library(readxl)
library(plm)
```

```{r Data Loading and Prep, results='hide'}
# Census Data
vars <- load_variables(2016, "acs5")
census_data <- get_acs(
  geography = "state", 
  variables = c(total_pop = "B01001_001", 
                med_income = "B06011_001", 
                unemployed = "B23025_005", 
                HSdegree = "B15003_017", 
                white_poverty = "B17001A_002", 
                white_pop = "B01001A_001"),
  year = 2016,
  geometry = TRUE,
  shift_geo = TRUE
) %>% 
  select(-moe) %>%
  spread(variable, estimate) %>% 
  mutate(pct_unemployed = unemployed / total_pop,
         pct_HSdegree = HSdegree / total_pop,
         pct_white_poverty = white_poverty / total_pop,
         pct_non_white = 1 - white_pop /total_pop)

# Non-citizen Data
non_citizen <- read_csv("raw_data_2017.csv", skip = 2) %>% 
  rename("NAME" = "Location") %>%
  mutate(pct_non_citizen = `Non-Citizen` / Total) %>% 
  select(1, 6)

# GINI Index
GINI <- read_csv("ACS_17_1YR_B19083_with_ann.csv") %>% 
  select(3:4) %>% 
  rename("NAME" = "GEO.display-label", "gini_index" = "HD01_VD01")
  
GINI$gini_index <- as.numeric(GINI$gini_index)

# LGBT Population Data (Source: Gallup)
lgbt <- read_excel("GallupAnalytics_Export_20190712_095942.xlsx", skip = 6) %>% 
  filter(Time == 2016) %>% 
  rename("NAME" = "Geography", "pct_lgbt" = "Yes, do") %>% 
  select(1, 5)

# Religious Demographic Data (Source: Gallup)
religion <- read_excel("GallupAnalytics_Export_20190712_093533.xlsx", skip = 6) %>% 
  filter(Time == 2016) %>% 
  rename("NAME" = "Geography", "pct_muslim" = "Muslim") %>% 
  select(1, 7)

# Hate Crime Data (Source: FBI)
hate_crime <- read_excel("Table_12_Agency_Hate_Crime_Reporting_by_State_2017.xls", skip = 2) %>% 
  rename("NAME" = "Participating state", "pop_covered" = "Population\ncovered") %>% 
  mutate(avg_hate_crime = 
           `Total\nnumber of\nincidents\nreported` / 
           pop_covered * 100000) %>% 
  select(1, 3, 9)

# Combining Data
data_2017 <- census_data %>% 
  left_join(GINI, by = "NAME") %>% 
  left_join(non_citizen, by = "NAME") %>% 
  left_join(lgbt, by = "NAME") %>%
  left_join(religion, by = "NAME") %>%
  left_join(hate_crime, by = "NAME") %>% 
  filter(!NAME %in% c("Puerto Rico")) %>% 
  mutate(med_income_square = med_income^2,
         pct_unemployed_square = pct_unemployed^2,
         pct_HSdegree_square = pct_HSdegree^2,
         pct_white_poverty_square = pct_white_poverty^2,
         pct_non_white_square = pct_non_white^2,
         gini_index_square = gini_index^2,
         pct_non_citizen_square = pct_non_citizen^2,
         pct_lgbt_square = pct_lgbt^2,
         pct_muslim_square = pct_muslim^2,
         pct_pop_covered = pop_covered / total_pop)

```

```{r Regression with 2017 data, eval = FALSE}
data_2017_2 <- data_2017 %>% 
  filter(!NAME %in% c("District of Columbia", "Hawaii"))
  
model_1 <- lm(avg_hate_crime ~ med_income + pct_unemployed + pct_HSdegree +
              pct_white_poverty + pct_non_white + gini_index + pct_non_citizen + 
              pct_lgbt + pct_muslim + pct_pop_covered, data = data_2017_2)

model_2 <- lm(avg_hate_crime ~ med_income + med_income_square + pct_unemployed + 
                    pct_unemployed_square + pct_HSdegree + pct_HSdegree_square +
                    pct_white_poverty + pct_white_poverty_square + pct_non_white + 
                    pct_non_white_square + gini_index + gini_index_square +
                    pct_non_citizen + pct_non_citizen_square +
                    pct_lgbt + pct_lgbt_square + pct_muslim + pct_muslim_square +
                    pct_pop_covered, data = data_2017_2)

model_3 <- lm(avg_hate_crime ~ med_income + med_income_square + 
                    pct_unemployed * pct_non_citizen + pct_unemployed_square + 
                    pct_white_poverty * pct_non_white + pct_white_poverty_square + pct_non_white_square +
                    pct_HSdegree * gini_index + gini_index_square + pct_non_citizen_square + 
                    pct_HSdegree_square + pct_lgbt + pct_lgbt_square + pct_muslim + 
                    pct_muslim_square + pct_pop_covered, data = data_2017_2)

stargazer(model_1, model_2, model_3, type='text', title = "Regression Results",
          header = FALSE, font.size = "small", column.sep.width = "1pt", single.row = TRUE, 
          dep.var.labels = "Avg. Annual Hate Crimes per 100k Pop.",
          covariate.labels = c("Median Income", "Median Income$^{2}$", "Pct. Unemployed", 
                               "Pct. Unemployed$^{2}$", "Pct. Only HS degree", 
                               "Pct. Only HS degree$^{2}$", "Pct. White poverty", 
                               "Pct. White poverty$^{2}$", "Pct. Non-white", "Pct. Non-white$^{2}$",
                               "GINI index", "GINI index$^{2}$", "Pct. Non-citizen", 
                               "Pct. Non-citizen$^{2}$", "Pct. LGBT",  "Pct. LGBT$^{2}$",
                               "Pct. Muslim", "Pct. Muslim$^{2}$", "Pct. Pop. Covered", 
                               "Pct. Unemployed * Pct. Non-citizen", 
                               "Pct. White poverty * Pct. Non-white",
                               "Pct. Only HS degree * GINI index"))
```


```{r Hate Crime Map}
data_2017 %>% 
  filter(NAME != "District of Columbia") %>% 
  st_transform(2163) %>%
  ggplot() +
    geom_sf(aes(fill = avg_hate_crime)) +
    scale_fill_distiller(palette = "YlOrRd",
                         direction = 1,
                         name = "Avg. Annual\nHate Crimes\nper 100k Pop.") +
    annotate("text", -Inf, -Inf, 
             label = "No Data", colour = "grey", hjust = -3.5, vjust = -1.5) +
    labs(
      title="U.S. Hate Crime Rates (2017)",
      caption="Source: FBI") +
    theme_void()
```


```{r Change in Hate Crimes Plot}
hate_crime_agg <- tibble()

for (i in 2008:2017) {
  name <- paste("table_12_agency_hate_crime_reporting_by_state_", i, ".xls", sep = "")
  hate_crime_yearly <- read_excel(name, skip = 4, col_names = FALSE) %>% 
    rename("NAME" = "...1", "pop_covered" = "...3") %>% 
    mutate(avg_hate_crime = ...5 / pop_covered * 100000, year = i) %>% 
    select(NAME, year, avg_hate_crime, pop_covered) 
  hate_crime_agg <- bind_rows(hate_crime_agg, hate_crime_yearly)
}

hate_crime_agg <- hate_crime_agg %>% 
  filter(NAME %in% c(state.name, "District of Columbia"))

hate_crime_vol <- hate_crime_agg %>%
  group_by(NAME) %>% 
  summarize(volatility = sd(avg_hate_crime)) %>% 
  arrange(desc(volatility))

ggplot()+
  geom_smooth(data =filter(hate_crime_agg, 
                           !NAME %in% c("District of Columbia", 
                                        "North Dakota", 
                                        "New Jersey",
                                        "Kentucky",
                                        "Delaware",
                                        "South Dakota")), 
              aes(x = year, y = avg_hate_crime, group = NAME), 
              color = "grey", size = 0.5, se = FALSE) +
  geom_smooth(data =filter(hate_crime_agg, NAME == "North Dakota"), 
              aes(x = year, y = avg_hate_crime, group = NAME), 
              color = "#800026", size = 1, se = FALSE) +
  annotate("text", x = 2017.2, y = 1.9877976, label = "ND", colour = "#800026", vjust = 2) +
  geom_smooth(data =filter(hate_crime_agg, NAME == "South Dakota"), 
              aes(x = year, y = avg_hate_crime, group = NAME), 
              color = "#bd0026", size = 1, se = FALSE) +
  annotate("text", x = 2017.2, y = 2.1274386, label = "SD", colour = "#bd0026", vjust = 0) +
  geom_smooth(data =filter(hate_crime_agg, NAME == "Delaware"), 
              aes(x = year, y = avg_hate_crime, group = NAME), 
              color = "#fc4e2a", size = 1, se = FALSE) +
  annotate("text", x = 2017.2, y = 3.0147442, label = "DE", colour = "#fc4e2a", vjust = 0) +
  geom_smooth(data =filter(hate_crime_agg, NAME == "Kentucky"), 
              aes(x = year, y = avg_hate_crime, group = NAME), 
              color = "#fd8d3c", size = 1, se = FALSE) +
  annotate("text", x = 2017.2, y = 8.50539316, label = "KY", colour = "#fd8d3c", vjust = 1) +
  geom_smooth(data =filter(hate_crime_agg, NAME == "New Jersey"), 
              aes(x = year, y = avg_hate_crime, group = NAME), 
              color = "#feb24c", size = 1, se = FALSE) +
  annotate("text", x = 2017.2, y = 5.49655305, label = "NJ", colour = "#feb24c", vjust = 1) +
  labs(title="Changes in U.S. Hate Crime Rates (2008 - 2017)",
       subtitle = "The five most volatile states are colored and labeled.",
       caption="Source: FBI",
       x = "Year",
       y = "Avg. Annual Hate Crimes per 100k Pop.") +
  scale_x_continuous(breaks = c(2008:2017)) +
  theme_minimal()

```

```{r Panel Data Prep and Regression (with time FE), results='asis'}
# Census Data
data_agg <- tibble()

for (i in 2012:2016) {
census_yearly <- get_acs(
  geography = "state", 
  variables = c(total_pop = "B01001_001", 
                med_income = "B06011_001", 
                unemployed = "B23025_005", 
                HSdegree = "B15003_017",
                HSdegree_alt = "B15003_018",
                white_poverty = "B17001A_002", 
                white_pop = "B01001A_001"),
  year = i) %>% 
  select(-moe, - GEOID) %>%
  spread(variable, estimate) %>% 
  mutate(pct_unemployed = unemployed / total_pop,
         pct_HSdegree = (HSdegree + HSdegree_alt) / total_pop,
         pct_white_poverty = white_poverty / total_pop,
         pct_non_white = 1 - white_pop /total_pop) %>% 
  mutate(year = i) %>% 
  select(-unemployed, -HSdegree, -HSdegree_alt, -white_poverty, -white_pop)
data_agg <- bind_rows(data_agg, census_yearly)
}

# GINI Index
gini_index_agg <- tibble()

for (i in 12:16) {
  name <- paste("ACS_", i, "_5YR_B19083_with_ann.csv", sep = "")
  gini_index_yearly <- read_csv(name) %>% 
    select(3:4) %>% 
    rename("NAME" = "GEO.display-label", "gini_index" = "HD01_VD01") %>% 
    mutate(year = as.numeric(paste("20", i, sep = "")),
           gini_index = as.numeric(gini_index)) %>% 
    filter(NAME != "Geography")
  gini_index_agg <- bind_rows(gini_index_agg, gini_index_yearly)
}

# Non-citizen Data
non_citizen_agg <- tibble()

for (i in 2012:2016) {
  name <- paste("raw_data_", i, ".csv", sep = "")
  non_citizen_yearly <- read_csv(name, skip = 2) %>% 
    rename("NAME" = "Location") %>%
    mutate(pct_non_citizen = `Non-Citizen` / Total,
           year = i) %>% 
    select(NAME, pct_non_citizen, year) %>% 
    filter(NAME %in% c(state.name, "District of Columbia"))
  non_citizen_agg <- bind_rows(non_citizen_agg, non_citizen_yearly)
}

# Ideology Data
ideology_agg <- read_dta("stateideology_v2018.dta") %>% 
  rename("NAME" = "statename", "citizen_ideology" = "citi6016") %>% 
  select(NAME, year, citizen_ideology) %>% 
  filter(year == c(2012:2016))

# Religion Data
religion_agg <- read_excel("GallupAnalytics_Export_20190712_093533.xlsx", skip = 6) %>% 
  rename("NAME" = "Geography", "pct_muslim" = "Muslim", "year" = "Time") %>%
  mutate(year = as.numeric(year)) %>% 
  select(1, 2, 7)

# LGBT Data
lgbt_agg <- read_excel("GallupAnalytics_Export_20190712_095942.xlsx", skip = 6) %>% 
  rename("NAME" = "Geography", "pct_lgbt" = "Yes, do", "year" = "Time") %>% 
  mutate(year = as.numeric(year)) %>% 
  select(1, 2, 5)

# Merge
data_agg <- data_agg %>%
  left_join(hate_crime_agg, by = c("NAME", "year")) %>%
  left_join(religion_agg, by = c("NAME", "year")) %>%
  left_join(non_citizen_agg, by = c("NAME", "year")) %>%
  left_join(lgbt_agg, by = c("NAME", "year")) %>%
  left_join(gini_index_agg, by = c("NAME", "year")) %>%
  filter(!NAME %in% c("Puerto Rico", "Hawaii", "District of Columbia")) %>% 
  mutate(med_income_square = med_income^2,
         pct_unemployed_square = pct_unemployed^2,
         pct_HSdegree_square = pct_HSdegree^2,
         pct_white_poverty_square = pct_white_poverty^2,
         pct_non_white_square = pct_non_white^2,
         gini_index_square = gini_index^2,
         pct_non_citizen_square = pct_non_citizen^2,
         pct_lgbt_square = pct_lgbt^2,
         pct_muslim_square = pct_muslim^2,
         pct_pop_covered = pop_covered / total_pop) %>% 
  arrange(NAME)

# Regression
model_agg1 <- plm(avg_hate_crime ~ med_income + pct_unemployed + pct_HSdegree +
              pct_white_poverty + pct_non_white + gini_index + pct_non_citizen + 
              pct_lgbt + pct_muslim + pct_pop_covered, data = data_agg, 
              index = c("NAME", "year"), model = "within", effect = "time")

model_agg2 <- plm(avg_hate_crime ~ med_income + med_income_square + pct_unemployed + 
                    pct_unemployed_square + pct_HSdegree + pct_HSdegree_square +
                    pct_white_poverty + pct_white_poverty_square + pct_non_white + 
                    pct_non_white_square + gini_index + gini_index_square +
                    pct_non_citizen + pct_non_citizen_square +
                    pct_lgbt + pct_lgbt_square + pct_muslim + pct_muslim_square +
                    pct_pop_covered, 
              data = data_agg, 
              index = c("NAME", "year"), model = "within", effect = "time")

model_agg3 <- plm(avg_hate_crime ~ med_income + med_income_square + 
                    pct_unemployed * pct_non_citizen + pct_unemployed_square + 
                    pct_white_poverty * pct_non_white + pct_white_poverty_square + pct_non_white_square +
                    pct_HSdegree * gini_index + gini_index_square + pct_non_citizen_square +
               pct_HSdegree_square +
              pct_lgbt + pct_lgbt_square + pct_muslim + pct_muslim_square + pct_pop_covered, 
              data = data_agg, 
              index = c("NAME", "year"), model = "within", effect = "time")

stargazer(model_agg1, model_agg2, model_agg3, type='latex', title = "Regression Results",
          header = FALSE, font.size = "small", column.sep.width = "1pt", single.row = TRUE, 
          dep.var.labels = "Avg. Annual Hate Crimes per 100k Pop.",
          notes = "Time fixed effects not shown.",
          covariate.labels = c("Median Income", "Median Income$^{2}$", "Pct. Unemployed", 
                               "Pct. Unemployed$^{2}$", "Pct. Only HS degree", 
                               "Pct. Only HS degree$^{2}$", "Pct. White poverty", 
                               "Pct. White poverty$^{2}$", "Pct. Non-white", "Pct. Non-white$^{2}$",
                               "GINI index", "GINI index$^{2}$", "Pct. Non-citizen", 
                               "Pct. Non-citizen$^{2}$", "Pct. LGBT",  "Pct. LGBT$^{2}$",
                               "Pct. Muslim", "Pct. Muslim$^{2}$", "Pct. Pop. Covered", 
                               "Pct. Unemployed * Pct. Non-citizen", 
                               "Pct. White poverty * Pct. Non-white",
                               "Pct. Only HS degree * GINI index"))
```

```{r Panel Data Regression without fixed effects, eval = FALSE}
# Regression
model_agg4 <- lm(avg_hate_crime ~ med_income + pct_unemployed + pct_HSdegree +
              pct_white_poverty + pct_non_white + gini_index + pct_non_citizen + 
              pct_lgbt + pct_muslim + pct_pop_covered, data = data_agg)

model_agg5 <- lm(avg_hate_crime ~ med_income + med_income_square + pct_unemployed + 
                    pct_unemployed_square + pct_HSdegree + pct_HSdegree_square +
                    pct_white_poverty + pct_white_poverty_square + pct_non_white + 
                    pct_non_white_square + gini_index + gini_index_square +
                    pct_non_citizen + pct_non_citizen_square +
                    pct_lgbt + pct_lgbt_square + pct_muslim + pct_muslim_square +
                    pct_pop_covered, data = data_agg)

model_agg6 <- lm(avg_hate_crime ~ med_income + med_income_square + 
                    pct_unemployed * pct_non_citizen + pct_unemployed_square + 
                    pct_white_poverty * pct_non_white + pct_white_poverty_square + pct_non_white_square +
                    pct_HSdegree * gini_index + gini_index_square + pct_non_citizen_square + 
                    pct_HSdegree_square + pct_lgbt + pct_lgbt_square + pct_muslim + 
                    pct_muslim_square + pct_pop_covered, data = data_agg)

stargazer(model_agg4, model_agg5, model_agg6, type='text', title = "Regression Results",
          header = FALSE, font.size = "small", column.sep.width = "1pt", single.row = TRUE, 
          dep.var.labels = "Avg. Annual Hate Crimes per 100k Pop.",
          covariate.labels = c("Median Income", "Median Income$^{2}$", "Pct. Unemployed", 
                               "Pct. Unemployed$^{2}$", "Pct. Only HS degree", 
                               "Pct. Only HS degree$^{2}$", "Pct. White poverty", 
                               "Pct. White poverty$^{2}$", "Pct. Non-white", "Pct. Non-white$^{2}$",
                               "GINI index", "GINI index$^{2}$", "Pct. Non-citizen", 
                               "Pct. Non-citizen$^{2}$", "Pct. LGBT",  "Pct. LGBT$^{2}$",
                               "Pct. Muslim", "Pct. Muslim$^{2}$", "Pct. Pop. Covered", 
                               "Pct. Unemployed * Pct. Non-citizen", 
                               "Pct. White poverty * Pct. Non-white",
                               "Pct. Only HS degree * GINI index"))
  
```

